### ISSUE TITLE
Ability to pull in rules from remote repos

### ISSUE THREAD

**Issue by armanrahman22** [inclusive-dev-tools/woke#1]
Right now the code looks locally for the rules file, but we want to be able to source it from any public URL to allow for reuse of external rule sets

Acceptance Criteria:

- Ability to run the linter on a publicly accessible ruleset file by pointing to it in the cli arguments. e.g. `woke -c https://raw.githubusercontent.com/get-woke/woke/main/example.yaml`

**Comment by mkcomer** [comment]
When setting a custom config, I noticed:

if rule set is contents is "hello" --> we get error 
 FTL  error="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `hello` into config.Config"
exit status 1

if rule set contents is "404: Not Found" --> no error, believes it is a valid yaml, but then doesn't add the custom rules. 

Suggested enhancement: 
1. Easier lift - add error handling to adding to rulesets - if it fails, tell us your config was invalid and we didn't add your rules.
2. Larger lift - Add a schema validator for custom yaml file + add error handling while parsing yaml for contents.
