### ISSUE TITLE
Add Azure Boards View

### ISSUE THREAD

**Issue by armanrahman22** [inclusive-dev-tools/woke#4]
Integrate the Github project board with Azure Boards: https://docs.microsoft.com/en-us/azure/devops/boards/github/?view=azure-devops

[AB#414](https://dev.azure.com/csenyc/7e20808a-c7db-4d65-bdc7-24193625ee11/_workitems/edit/414)
AB#

Acceptance Criteria:

- Able to view the github project board as an Azure Board
- Check to see if we have all the needed functionality to use it for standups and planning
- Check to see if changes on the Azure Board are reflected on the github board

**Comment by mschrayms** [comment]
@armanrahman22 I am not sure I have sufficient rights to do the install.  If I initiate from my personal account I can't see the repo.  I think that makes sense.  I go to this repo and go to integrations (https://github.com/inclusive-dev-tools/woke/settings/installations) and I don't see any buttons to do anything.

**Comment by armanrahman22** [comment]
@mschrayms I added the azure boards app to the project and created a devops project here (https://dev.azure.com/csenyc/woke/_workitems/recentlyupdated/) which is linked to it, but i'm not sure how to get github issues to appear on the board.

**Comment by mschrayms** [comment]
@armanrahman22 I'll take it from here and work out the next set of integration details.  Thank you.

**Comment by mschrayms** [comment]
@armanrahman22 I sent an request from the SharkCatWoke Azure Board to get access to our repo.  As owner you'll see it.  Please approve. Hopefully, I helps with this error message.

![image](https://user-images.githubusercontent.com/22949865/126582489-c47b7ea7-ea87-4358-a4b5-8c13b093bd61.png)

**Comment by mschrayms** [comment]
The wire up seems to be complete now...  Once Arman granted access, I have able to connect to the Woke GH repo.  Now to work out details on make them really work together.
![image](https://user-images.githubusercontent.com/22949865/126645740-988888e6-b052-485c-a1c6-4a7be9fd23cb.png)

**Comment by mschrayms** [comment]
@sbohlen and @fnocera I am not sure that right now there is value in connecting Azure Boards to Github.  The gist of what the capabilities are is described [here](https://docs.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-mention-to-link-from-github-to-azure-boards-work-items).  Basically you can refer to a AB item from GH it will automatically link them up using ABhastag{id}.  To me this seems we would need to keep a duplicate item in AB to point to GH.  Additionally, I don't see a way to create an item in AB that is represented in GH (without creating one in each location), which would seem like the ideal approach.  Let me know if I missed something that we would see as valuable.  Perhaps a snack talk to share learnings with the team and activate the team to see if there is more to this that I missed.

**Comment by sbohlen** [comment]
@mschrayms I tend to agree that there's not much value in the cross-system linking/references (at least not in the context of the `woke` project work where we're forked/working in GitHub already).  I *think* that the initial idea was to gain some value from [visualizing github work items on the AzDO kanban board](https://docs.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#view-github-objects-on-kanban-board), but I think you're raising an important point that there may not be as much value there as anticipated (?)

I like the idea of having a further discussion about this in the next QwckBits session to get other inputs/thoughts and reach a shared understanding + group decision re: the value-prop -- good suggestion!
