### ISSUE TITLE
Improve Default Ignore Rules

### ISSUE THREAD

**Issue by armanrahman22** [inclusive-dev-tools/woke#9]
Original Issue: https://github.com/get-woke/woke/issues/58

Add sensible default ignore files (e.g. commonly autogenerated files, packages, etc.) to woke.

Acceptance Criteria:

- Commonly autogenerated files are ignored by default

**Comment by KSLHacks** [comment]
Reading through the original issue it identifies a need to ignore generated code such as lock files that contain SHAs. Going through common auto generated files by language.

**Comment by KSLHacks** [comment]
Link to upstream PR: https://github.com/get-woke/woke/pull/115
